name: Deploy to WafaiCloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BI_SSH_HOST }}
          username: ${{ secrets.BI_SSH_USER }}
          port: ${{ secrets.BI_SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            cd /var/www/webroot/ROOT
            git pull origin main
            npm install
            npx prisma generate
            pm2 restart backend